#!/bin/bash
# darwin/functions/helpers.sh
# macOS helper functions used by installEmuMacOS.sh and emulator scripts.
# Sourced only when system=darwin (via darwin/functions/all.sh).

# ─────────────────────────────────────────────
# mac_arch
# Returns: arm64 | x86_64
# ─────────────────────────────────────────────
mac_arch() {
    uname -m
}

# ─────────────────────────────────────────────
# mac_app_installed <AppName.app>
# Returns: "true" | "false"
# Checks /Applications first, then ~/Applications
# ─────────────────────────────────────────────
mac_app_installed() {
    local appName="$1"
    if [ -d "/Applications/${appName}" ] || [ -d "${HOME}/Applications/${appName}" ]; then
        echo "true"
    else
        echo "false"
    fi
}

# ─────────────────────────────────────────────
# mac_app_path <AppName.app>
# Returns the full path to the installed app, or empty string if not found
# ─────────────────────────────────────────────
mac_app_path() {
    local appName="$1"
    if [ -d "/Applications/${appName}" ]; then
        echo "/Applications/${appName}"
    elif [ -d "${HOME}/Applications/${appName}" ]; then
        echo "${HOME}/Applications/${appName}"
    else
        echo ""
    fi
}

# ─────────────────────────────────────────────
# mac_unquarantine <path>
# Removes the macOS quarantine extended attribute.
# Cask handles this automatically; call for DMG/ZIP installs.
# ─────────────────────────────────────────────
mac_unquarantine() {
    local targetPath="$1"
    if [ -e "$targetPath" ]; then
        xattr -cr "$targetPath" 2>/dev/null || true
        echo "[mac] Cleared quarantine: $targetPath"
    fi
}

# ─────────────────────────────────────────────
# mac_get_gh_release_url <owner/repo> <pattern>
# Returns the download URL for the first matching asset in the latest GH release.
# Pattern is a grep-E regex (e.g. "rpcs3-.*arm64.*\.dmg").
# Falls back to second-pattern if first returns empty.
# ─────────────────────────────────────────────
mac_get_gh_release_url() {
    local repo="$1"
    local pattern="$2"
    local fallbackPattern="${3:-}"

    local apiUrl="https://api.github.com/repos/${repo}/releases/latest"
    local url

    url=$(curl -s "$apiUrl" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        | jq -r --arg pat "$pattern" \
            '.assets[] | select(.name | test($pat; "i")) | .browser_download_url' \
        | head -1)

    if [ -z "$url" ] && [ -n "$fallbackPattern" ]; then
        url=$(curl -s "$apiUrl" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            | jq -r --arg pat "$fallbackPattern" \
                '.assets[] | select(.name | test($pat; "i")) | .browser_download_url' \
            | head -1)
    fi

    echo "$url"
}

# ─────────────────────────────────────────────
# mac_get_gh_release_url_arch <owner/repo> <arm64-pattern> <x86_64-pattern>
# Picks pattern based on current CPU arch, falls back to x86_64 on unknown.
# ─────────────────────────────────────────────
mac_get_gh_release_url_arch() {
    local repo="$1"
    local arm64Pattern="$2"
    local x64Pattern="$3"
    local anyPattern="${4:-}"

    local arch
    arch=$(mac_arch)

    local url
    if [ "$arch" = "arm64" ]; then
        url=$(mac_get_gh_release_url "$repo" "$arm64Pattern" "$anyPattern")
    else
        url=$(mac_get_gh_release_url "$repo" "$x64Pattern" "$anyPattern")
    fi

    echo "$url"
}

# ─────────────────────────────────────────────
# mac_deploy_launcher <launcherName> <appPath> [extraArgs]
# Creates a thin open-a launcher at ${toolsPath}/launchers/<launcherName>.sh
# and copies it to ${romsPath}/emulators/ (same as installEmuAI does on Linux).
# launcherName: e.g. "dolphin" (becomes dolphin.sh)
# appPath:      e.g. "/Applications/Dolphin.app"
# extraArgs:    optional args inserted between `open -a App.app` and `"$@"`
# ─────────────────────────────────────────────
mac_deploy_launcher() {
    local launcherName="$1"
    local appPath="$2"
    local extraArgs="${3:-}"

    local launcherFile="${toolsPath}/launchers/${launcherName}.sh"

    mkdir -p "${toolsPath}/launchers"
    mkdir -p "${romsPath}/emulators"

    cat > "$launcherFile" << LAUNCHER
#!/bin/bash
# EmuDeck macOS launcher: ${launcherName}
# Auto-generated by installEmuMacOS.sh — do not edit manually.
exec open -a "${appPath}" ${extraArgs} --args "\$@"
LAUNCHER

    chmod +x "$launcherFile"
    cp -f "$launcherFile" "${romsPath}/emulators/${launcherName}.sh"
    chmod +x "${romsPath}/emulators/${launcherName}.sh"

    echo "[mac] Deployed launcher: ${launcherFile}"
}

# ─────────────────────────────────────────────
# mac_uninstall_app <AppName.app>
# Moves the app to Trash via AppleScript (preserves user undo).
# Falls back to rm -rf if osascript fails.
# ─────────────────────────────────────────────
mac_uninstall_app() {
    local appName="$1"
    local appPath
    appPath=$(mac_app_path "$appName")

    if [ -z "$appPath" ]; then
        echo "[mac] $appName not found in /Applications or ~/Applications — nothing to uninstall."
        return 0
    fi

    # Try AppleScript Trash first (undo-able)
    if osascript -e "tell application \"Finder\" to move POSIX file \"${appPath}\" to trash" 2>/dev/null; then
        echo "[mac] Moved to Trash: ${appPath}"
    else
        # Fallback: hard delete
        rm -rf "$appPath"
        echo "[mac] Deleted: ${appPath}"
    fi
}

# ─────────────────────────────────────────────
# mac_ensure_dir <path>
# mkdir -p wrapper with a log message.
# ─────────────────────────────────────────────
mac_ensure_dir() {
    local dir="$1"
    mkdir -p "$dir"
}

# ─────────────────────────────────────────────
# mac_link_save <emuKey> <srcRelativePath> <destAbsolutePath>
# Creates a symlink from destAbsolutePath → the EmuDeck save location.
# srcRelativePath is relative to ~/Library/Application Support/
# Example: mac_link_save "rpcs3" "rpcs3/dev_hdd0" "$storagePath/rpcs3/dev_hdd0"
# ─────────────────────────────────────────────
mac_link_save() {
    local emuKey="$1"
    local srcRelPath="$2"     # e.g. "rpcs3/dev_hdd0" relative to ~/Library/Application Support/
    local destAbsPath="$3"    # e.g. "$storagePath/rpcs3/dev_hdd0"

    local srcAbs="${HOME}/Library/Application Support/${srcRelPath}"
    local srcParent
    srcParent="$(dirname "$srcAbs")"

    # Ensure destination exists
    mkdir -p "$destAbsPath"
    mkdir -p "$srcParent"

    # Remove existing dir/symlink at src, create symlink
    if [ -L "$srcAbs" ]; then
        rm "$srcAbs"
    elif [ -d "$srcAbs" ]; then
        # Move existing data to dest first
        rsync -a "$srcAbs/" "$destAbsPath/" 2>/dev/null || true
        rm -rf "$srcAbs"
    fi

    ln -sf "$destAbsPath" "$srcAbs"
    echo "[mac] Linked: ${srcAbs} → ${destAbsPath}"
}
